### PR TITLE
Remove superflous `image`-type

### PR DESCRIPTION
**Pull request by herschel666**
`mime.lookup` returns a fully qualified mime-type, not only the extension.

(https://www.npmjs.com/package/mime#mimelookuppath)

### CODE REVIEW

**Comment by nesQuick** [comment]
AFAIR this is required by our backend, please talk to @HenrikFricke and check the naked-lunch code base together before getting this in. Or wait until I'll return from parental leave :)

**Comment by herschel666** [comment]
I stumbled upon this one while trying to get the template-upload to work. As @HenrikFricke fixed that already, I actually don't care much about this PR here anymore … :-p

**Comment by nesQuick** [comment]
Just had time to check, and yes, it can't be removed because the API expect it: https://github.com/Jimdo/naked-lunch/blob/master/app/models/picture_asset.rb#L3

**Comment by herschel666** [comment]
Okay, you got me wrong. As far as I can confirm, `mime.lookup()` returns `image/<type>`. So there is no need to insert the string `image/` at that location. Can you confirm that, too?

**Comment by nesQuick** [comment]
Oh yeah, I got that wrong. sorry, I will check that within the next week

**Pull request merged**
